version: "3.7"

services:
  fastapi:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ddakkm_api
    environment:
      app_env: dev
    depends_on:
      - nginx

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    build:
#      context: ./nginx
#      dockerfile: ./Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"