"""ADD Character Image

Revision ID: 037c36f9e2af
Revises: 360ca24d9ec3
Create Date: 2021-10-27 00:40:34.521311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037c36f9e2af'
down_revision = '360ca24d9ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('character_image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'character_image')
    # ### end Alembic commands ###
