"""ADD push_noti_agree

Revision ID: 0e2bfe99cadb
Revises: 037c36f9e2af
Create Date: 2021-10-31 22:25:57.704022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2bfe99cadb'
down_revision = '037c36f9e2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('agree_push', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'agree_push')
    # ### end Alembic commands ###
