"""add  is_join_survey to survey model

Revision ID: 13e8b0196f4b
Revises: 2ea3902d914a
Create Date: 2021-11-27 21:51:00.838509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e8b0196f4b'
down_revision = '2ea3902d914a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_a', sa.Column('is_join_survey', sa.Boolean(), nullable=True))
    op.add_column('survey_b', sa.Column('is_join_survey', sa.Boolean(), nullable=True))
    op.add_column('survey_c', sa.Column('is_join_survey', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_c', 'is_join_survey')
    op.drop_column('survey_b', 'is_join_survey')
    op.drop_column('survey_a', 'is_join_survey')
    # ### end Alembic commands ###
