"""ADD Comment-Review relationship

Revision ID: 1c32d036d5b6
Revises: 3ee8635ed08f
Create Date: 2021-10-10 16:00:10.406040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c32d036d5b6'
down_revision = '3ee8635ed08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_delete')
    # ### end Alembic commands ###
