"""add user_keyword

Revision ID: 2521fc62836e
Revises: 9f8455c2c8ef
Create Date: 2021-11-04 23:56:56.783712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2521fc62836e'
down_revision = '9f8455c2c8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_keyword',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_keyword_id'), 'user_keyword', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_keyword_id'), table_name='user_keyword')
    op.drop_table('user_keyword')
    # ### end Alembic commands ###
