"""EDIT agree policy

Revision ID: 360ca24d9ec3
Revises: 19b79563dccf
Create Date: 2021-10-27 00:25:07.702408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '360ca24d9ec3'
down_revision = '19b79563dccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('agree_policy', sa.Boolean(), nullable=False))
    op.drop_column('user', 'agree_over_fourteen')
    op.drop_column('user', 'agree_privacy_policy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('agree_privacy_policy', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('agree_over_fourteen', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'agree_policy')
    # ### end Alembic commands ###
