"""ADD Column vaccine_round

Revision ID: 3ee8635ed08f
Revises: 
Create Date: 2021-10-04 16:19:52.742633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee8635ed08f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_a', sa.Column('vaccine_round', sa.Enum('FIRST', 'SECOND', 'THIRD', name='vaccineround'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_a', 'vaccine_round')
    # ### end Alembic commands ###
