"""ADD user_comment_like table

Revision ID: 4be1c8f1040c
Revises: 9f940d0b65ea
Create Date: 2021-10-31 22:54:42.012965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be1c8f1040c'
down_revision = '9f940d0b65ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_comment_like',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    op.create_index(op.f('ix_user_comment_like_comment_id'), 'user_comment_like', ['comment_id'], unique=False)
    op.create_index(op.f('ix_user_comment_like_user_id'), 'user_comment_like', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_comment_like_user_id'), table_name='user_comment_like')
    op.drop_index(op.f('ix_user_comment_like_comment_id'), table_name='user_comment_like')
    op.drop_table('user_comment_like')
    # ### end Alembic commands ###
