"""EDIT agree policy

Revision ID: 5d72ddec61c9
Revises: 79a7b77167c8
Create Date: 2021-11-03 00:27:33.184496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d72ddec61c9'
down_revision = '79a7b77167c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('agree_keyword_push', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('agree_activity_push', sa.Boolean(), nullable=False))
    op.drop_column('user', 'agree_push')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('agree_push', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'agree_activity_push')
    op.drop_column('user', 'agree_keyword_push')
    # ### end Alembic commands ###
