"""EDIT Comment table for nested comment model

Revision ID: 643102cebede
Revises: 1c32d036d5b6
Create Date: 2021-10-10 17:21:44.210551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643102cebede'
down_revision = '1c32d036d5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('depth', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'parent_id')
    op.drop_column('review', 'depth')
    # ### end Alembic commands ###
