"""Modify Survey Structure

Revision ID: 70de637dbb0b
Revises: a9f1b8538a85
Create Date: 2021-09-30 13:18:24.461883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70de637dbb0b'
down_revision = 'a9f1b8538a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_survey_x_id', table_name='survey_x')
    op.drop_table('survey_x')
    op.add_column('review', sa.Column('survey_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'survey_a', ['survey_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'survey_id')
    op.create_table('survey_x',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vaccine_type', mysql.ENUM('PFIZER', 'MODERNA', 'AZ', 'JANSSEN', 'ETC'), nullable=True),
    sa.Column('is_crossed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_pregnant', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_underlying_disease', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_from', mysql.ENUM('0', '2', '3', 'over5', 'over1week', 'over1month'), nullable=True),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name='survey_x_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_survey_x_id', 'survey_x', ['id'], unique=False)
    # ### end Alembic commands ###
