"""ADD relation

Revision ID: 79a7b77167c8
Revises: df5abb6546f0
Create Date: 2021-10-31 23:26:34.280998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a7b77167c8'
down_revision = 'df5abb6546f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
