"""add  qna table

Revision ID: 95118021d944
Revises: e70004a1fc07
Create Date: 2021-11-30 21:44:57.203706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95118021d944'
down_revision = 'e70004a1fc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qna',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=3000), nullable=True),
    sa.Column('user_email', sa.String(length=300), nullable=True),
    sa.Column('user_phone', sa.String(length=30), nullable=True),
    sa.Column('is_solved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qna_id'), 'qna', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qna_id'), table_name='qna')
    op.drop_table('qna')
    # ### end Alembic commands ###
