"""EDIT Comment table for nested comment model

Revision ID: 9aaf99078f07
Revises: 643102cebede
Create Date: 2021-10-10 17:22:35.889642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9aaf99078f07'
down_revision = '643102cebede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('depth', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_column('review', 'parent_id')
    op.drop_column('review', 'depth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('depth', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('review', sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comment', 'parent_id')
    op.drop_column('comment', 'depth')
    # ### end Alembic commands ###
