"""ADD user_comment_like table

Revision ID: 9f940d0b65ea
Revises: 0e2bfe99cadb
Create Date: 2021-10-31 22:54:18.223223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f940d0b65ea'
down_revision = '0e2bfe99cadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
