"""ADD relation

Revision ID: ac3aee5cc9af
Revises: eea80bd3255e
Create Date: 2021-10-31 23:17:36.718016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3aee5cc9af'
down_revision = 'eea80bd3255e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
