"""SET user model Email Not unique

Revision ID: d85679684fc5
Revises: 906d3ee13a32
Create Date: 2021-10-13 23:13:15.861857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85679684fc5'
down_revision = '906d3ee13a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
