"""ADD relation

Revision ID: df5abb6546f0
Revises: ac3aee5cc9af
Create Date: 2021-10-31 23:26:18.215308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5abb6546f0'
down_revision = 'ac3aee5cc9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
