"""add  qna table

Revision ID: e70004a1fc07
Revises: 13e8b0196f4b
Create Date: 2021-11-30 21:44:10.502101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70004a1fc07'
down_revision = '13e8b0196f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
