"""add constraint for review: like_count

Revision ID: e942fe13b290
Revises: 05aa1b6b8d6b
Create Date: 2021-11-16 23:26:09.804180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e942fe13b290'
down_revision = '05aa1b6b8d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'like_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'like_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
