"""ADD like_count column in comment

Revision ID: eea80bd3255e
Revises: 4be1c8f1040c
Create Date: 2021-10-31 23:10:04.187548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea80bd3255e'
down_revision = '4be1c8f1040c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'like_count')
    # ### end Alembic commands ###
